export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";
export const REQUEST_CATEGORIES = "REQUEST_CATEGORIES";
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER'

export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const RECEIVE_POST = "RECEIVE_POST";
export const REQUEST_POSTS = "REQUEST_POSTS";
export const CREATE_POST = "CREATE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const REMOVE_POST = "REMOVE_POST";
export const UPDATE_POST_DETAIL = "UPDATE_POST_DETAIL"
export const REMOVE_POST_DETAIL = "REMOVE_POST_DETAIL"

export const SORT_POST_BY_SCORE = "SORT_POST_BY_SCORE";
export const SORT_POST_BY_DATE = "SORT_POST_BY_DATE";

export const REQUEST_COMMENTS = "REQUEST_COMMENTS";
export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";

export const UPDATE_POST_SCORE = "UPDATE_POST_SCORE";
export const UPDATE_COMMENT_SCORE = "UPDATE_COMMENT_SCORE";
export const UPDATE_POST_SCORE_DETAIL = "UPDATE_POST_SCORE_DETAIL"

export const INCREMENT_POST_COMMENT_COUNT = "INCREMENT_POST_COMMENT_COUNT"
export const DECREMENT_POST_COMMENT_COUNT = "DECREMENT_POST_COMMENT_COUNT"